### ISSUE TITLE
Getting error while parsing scenes

### ISSUE THREAD

**Issue by Blackhawk0038** [cc1234475/stash-plugin-performer-creator#9]
I am getting below error while parsing my scenes, I have checked for the file under ner_model and could not find config.cfg.
Spacy configuration that I have is 3.4.1

What am I possibly doing wrong? Kindly help.

22-10-05 16:47:28Error   Plugin returned error: exit status 1
2022-10-05 16:47:28Error   [Plugin / Performer Creator] OSError: [E053] Could not read config file from D:\Tutorials\eclipse\features\org.eclipse.cft\META-INF\webapps\PS\Stash\Plugins\ner_model\config.cfg
2022-10-05 16:47:28Error   [Plugin / Performer Creator]     raise IOError(Errors.E053.format(path=config_path, name="config file"))
2022-10-05 16:47:28Error   [Plugin / Performer Creator]   File "D:\Tutorials\eclipse\features\org.eclipse.cft\META-INF\webapps\PS\Python\lib\site-packages\spacy\util.py", line 678, in load_config
2022-10-05 16:47:28Error   [Plugin / Performer Creator]     config = load_config(config_path, overrides=overrides)
2022-10-05 16:47:28Error   [Plugin / Performer Creator]   File "D:\Tutorials\eclipse\features\org.eclipse.cft\META-INF\webapps\PS\Python\lib\site-packages\spacy\util.py", line 502, in load_model_from_path
2022-10-05 16:47:28Error   [Plugin / Performer Creator]     return load_model_from_path(Path(name), **kwargs)  # type: ignore[arg-type]
2022-10-05 16:47:28Error   [Plugin / Performer Creator]   File "D:\Tutorials\eclipse\features\org.eclipse.cft\META-INF\webapps\PS\Python\lib\site-packages\spacy\util.py", line 431, in load_model
2022-10-05 16:47:28Error   [Plugin / Performer Creator]     return util.load_model(
2022-10-05 16:47:28Error   [Plugin / Performer Creator]   File "D:\Tutorials\eclipse\features\org.eclipse.cft\META-INF\webapps\PS\Python\lib\site-packages\spacy\__init__.py", line 54, in load
2022-10-05 16:47:28Error   [Plugin / Performer Creator]     nlp = spacy.load(model)
2022-10-05 16:47:28Error   [Plugin / Performer Creator]   File "D:\Tutorials\eclipse\features\org.eclipse.cft\META-INF\webapps\PS\Stash\plugins\performer_creator.py", line 17, in <module>
2022-10-05 16:47:28Error   [Plugin / Performer Creator] Traceback (most recent call last):

**Comment by cc1234475** [comment]
Hi @Blackhawk0038, the requirements at the moment are to use `spacy==2.3.5`.
Could you try with that?

**Comment by Blackhawk0038** [comment]
Thanks, works like a charm now.

Here is what I had to do extra, 
Installed latest MSVC toolset C++ 2019 and Visual C++ Build tools core features from here : https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019
For some reason spacy 2.3.5 was refusing to install without this. 

Also, had to do some changes as suggested in this issue,

https://github.com/cc1234475/stash-plugin-performer-creator
